.TH "NETGEN" "1" 
.SH "NAME" 
ng_stl  \(em Netgen (nglib) STL Testing 
.SH "SYNOPSIS" 
.PP 
\fBng_stl\fR [OPTIONS...]  [STL_filename]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBng_stl\fR and \fBbar\fR       commands. 
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
.PP 
\fBng_stl\fR is an STL testing utility for nglib. 
.PP 
Homepage: http://www.mathcces.rwth-aachen.de/netgen/doku.php 
.SH "AUTHOR" 
.PP 
This manual page was written by Christophe Trophime <christophe.trophime@grenoble.cnrs.fr> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Tue 16 Mar 2010, 10:36 
